[phases.setup]
nixPkgs = ["nodejs_20", "python310"]

[phases.install]
cmds = ["npm install", "pip install -r requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 backend/app/main.py"
